openapi: 3.0.3
info:
  title: myrecord APIs
  description: REST API for myrecord application
  version: 1.0.0
tags:
  - name: posts
paths:
  /posts:
    get:
      summary: get post list
      operationId: getPosts
      tags:
        - posts
      parameters:
        - name: user
          in: query
          required: false
          schema:
            type: string
          example: xxxxx@gmail.com
      responses:
        "200":
          description: OK
          content:
            'application/json':
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Post"
    post:
      summary: post new post
      operationId: postPost
      tags:
        - posts
      requestBody:
        description: post content
        required: true
        content:
          'application/json':
            schema:
              $ref: "#/components/schemas/PostRequestBody"
      responses:
        "201":
          description: CREATED
          content:
            'application/json':
              schema:
                $ref: "#/components/schemas/Post"
  /posts/{id}:
    get:
      summary: get post by id
      operationId: getPostById
      tags:
        - posts
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          example: xxxxxxxxxxxxxxxxxxxxx
      responses:
        "200":
          description: OK
          content:
            'application/json':
              schema:
                $ref: "#/components/schemas/Post"
    put:
      summary: update post by id
      operationId: putPost
      tags:
        - posts
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          example: xxxxxxxxxxxxxxxxxxxxx
      requestBody:
        description: put content
        required: true
        content:
          'application/json':
            schema:
              $ref: "#/components/schemas/PostRequestBody"
      responses:
        "200":
          description: OK
          content:
            'application/json':
              schema:
                $ref: "#/components/schemas/Post"
    delete:
      summary: delete post by id
      operationId: deletePost
      tags:
        - posts
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          example: xxxxxxxxxxxxxxxxxxxxx
      responses:
        "204":
          description: NO CONTENT
components:
  schemas:
    Post:
      type: object
      properties:
        id:
          type: string
        anime_name:
          type: string
        rating:
          type: integer
          format: int32
        delete_flag:
          type: integer
          format: int32
        user:
          type: string
        created_at:
          type: string
          format: date
        updated_at:
          type: string
          format: date
        deleted_at:
          type: string
          format: date
          example: null
    PostRequestBody:
      type: object
      properties:
        anime_name:
          type: string
        rating:
          type: integer
          format: int32
        user:
          type: string
      required:
        - anime_name
        - rating
        - user
